version: '3.0'

services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        env_file:
            - .env
        ports:
            - "5050:80"
        restart: unless-stopped

    library:
        container_name: service_library
        build:
            dockerfile: dockerfile
            context: ./library-go
        ports:
            - "1000:1000"
        env_file:
            - .env
        restart: always
        volumes:
            - ./logs:/logs
            - ./store:/store
        depends_on:
            - librarymigrate

    librarydb:
        container_name: db_library
        image: postgres:13-alpine
        env_file:
            - .env
        ports:
            - "1001:5432"
        restart: always
        volumes:
            - ./database/postgres/data:/var/lib/postgresql/data/


    librarymigrate:
        container_name: migrate_library
        image: migrate/migrate
        restart: on-failure
        volumes:
            - ./database/postgres/migrations:/database/postgres/migrations

        command:
            [
                "-path",
                "database/postgres/migrations",
                "-database",
                "postgres://user:12345@librarydb:5432/librarydb?sslmode=disable",
                "up"
            ]
        depends_on:
            - librarydb

